from __future__ import annotations

import argparse
import sys
from collections.abc import Callable
from pathlib import Path

from careervoice_ai_orchestrator import __version__
from careervoice_ai_orchestrator.command_runner import (
    CommandNotFoundError,
    CommandRunError,
    SupportsCommandRun,
)
from careervoice_ai_orchestrator.models import (
    SUPPORTED_INPUT_MODES,
    SUPPORTED_JOB_SOURCES,
    SUPPORTED_PROFILE_EXTRACTORS,
    SUPPORTED_RECOMMENDER_SCORERS,
    WorkflowConfig,
)
from careervoice_ai_orchestrator.workflow import run_workflow


def build_parser() -> argparse.ArgumentParser:
    """
    Build the command-line parser for the CareerVoice AI orchestrator.
    """
    parser = argparse.ArgumentParser(
        prog="careervoice-run",
        description=(
            "Run the CareerVoice AI orchestration workflow across profile "
            "extraction, job collection, and recommendation steps."
        ),
    )

    parser.add_argument(
        "--version",
        action="version",
        version=f"careervoice-ai-orchestrator {__version__}",
    )

    parser.add_argument(
        "--input-mode",
        choices=SUPPORTED_INPUT_MODES,
        default="profile",
        help=(
            "Input mode. Use 'profile' for an existing career_profile.json, "
            "'text' to type career preferences in the terminal, or 'voice' "
            "to call Repo 1 voice input."
        ),
    )

    parser.add_argument(
        "--profile-input",
        default="outputs/profile_input.txt",
        help="Path where terminal text input should be saved before Repo 1 reads it.",
    )

    parser.add_argument(
        "--profile",
        default=None,
        help=(
            "Path to career_profile.json. In profile mode this is an input file. "
            "In text or voice mode this is the profile output generated by Repo 1."
        ),
    )

    parser.add_argument(
        "--profile-extractor",
        choices=SUPPORTED_PROFILE_EXTRACTORS,
        default="rules",
        help="Profile extractor used by Repo 1.",
    )

    parser.add_argument(
        "--jobs-output",
        default="outputs/jobs.json",
        help="Path where collected jobs.json should be saved.",
    )

    parser.add_argument(
        "--recommendations-output",
        default="outputs/recommendations.json",
        help="Path where recommendations.json should be saved.",
    )

    parser.add_argument(
        "--source",
        choices=SUPPORTED_JOB_SOURCES,
        default="adzuna",
        help="Job listing source to use.",
    )

    parser.add_argument(
        "--query",
        dest="queries",
        action="append",
        default=None,
        help=(
            "Optional job search query. Repeat this option to provide multiple "
            "queries. When omitted, target_roles are read from the career profile."
        ),
    )

    parser.add_argument(
        "--location",
        default="Adelaide",
        help="Job search location. Use an empty string for no location.",
    )

    parser.add_argument(
        "--job-max-results",
        type=int,
        default=10,
        help="Maximum number of jobs to collect for each query.",
    )

    parser.add_argument(
        "--recommendation-max-results",
        type=int,
        default=10,
        help="Maximum number of ranked recommendations to return.",
    )

    parser.add_argument(
        "--scorer",
        choices=SUPPORTED_RECOMMENDER_SCORERS,
        default="rules",
        help="Recommendation scorer to use.",
    )

    parser.add_argument(
        "--exclude-rejected",
        action="store_true",
        help="Exclude jobs rejected by hard constraints.",
    )

    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show output captured from external repository commands.",
    )

    return parser


def resolve_profile_path(args: argparse.Namespace) -> Path:
    """
    Resolve the profile path based on the selected input mode.
    """
    if args.profile is not None:
        return Path(args.profile)

    if args.input_mode == "profile":
        return Path("examples/career_profile.json")

    return Path("outputs/career_profile.json")


def build_config_from_args(args: argparse.Namespace) -> WorkflowConfig:
    """
    Convert parsed CLI arguments into a WorkflowConfig object.
    """
    location = args.location.strip() if args.location is not None else ""

    return WorkflowConfig(
        input_mode=args.input_mode,
        profile_input_path=Path(args.profile_input),
        profile_path=resolve_profile_path(args),
        jobs_output_path=Path(args.jobs_output),
        recommendations_output_path=Path(args.recommendations_output),
        profile_extractor=args.profile_extractor,
        job_source=args.source,
        job_queries=tuple(args.queries or ()),
        job_location=location or None,
        job_max_results=args.job_max_results,
        recommender_scorer=args.scorer,
        recommendation_max_results=args.recommendation_max_results,
        exclude_rejected=args.exclude_rejected,
    )


def read_terminal_profile_text(input_func: Callable[[], str] = input) -> str:
    """
    Read multi-line career preference text from the terminal.

    The user finishes input by pressing Enter on an empty line.
    """
    print("Please enter your career preference.")
    print("Press Enter on an empty line when finished:")
    print()

    lines: list[str] = []

    while True:
        try:
            line = input_func()
        except EOFError:
            break

        if not line.strip():
            break

        lines.append(line)

    return "\n".join(lines)


def print_command_output(title: str, output: str) -> None:
    """
    Print captured command output when verbose mode is enabled.
    """
    cleaned_output = output.strip()

    if not cleaned_output:
        return

    print()
    print(title)
    print("-" * len(title))
    print(cleaned_output)


def print_job_queries(queries: tuple[str, ...]) -> None:
    """
    Print the resolved job search queries used by the workflow.
    """
    print()
    print("Job search queries:")

    for query in queries:
        print(f"- {query}")


def main(
    argv: list[str] | None = None,
    *,
    runner: SupportsCommandRun | None = None,
    input_reader: Callable[[], str] | None = None,
) -> int:
    """
    CLI entry point for the orchestrator.
    """
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        config = build_config_from_args(args)

        print("Running CareerVoice AI orchestrator...")

        profile_input_text: str | None = None

        if config.input_mode == "text":
            reader = input_reader or read_terminal_profile_text
            profile_input_text = reader()

        elif config.input_mode == "voice":
            print("Starting voice input through Repo 1...")

        result = run_workflow(
            config=config,
            profile_input_text=profile_input_text,
            runner=runner,
        )

        print_job_queries(result.job_queries)

        if args.verbose and result.profile_extraction_result is not None:
            print_command_output(
                "Profile extraction output",
                result.profile_extraction_result.stdout,
            )

        if args.verbose:
            print_command_output(
                "Job collection output",
                result.job_collection_result.stdout,
            )
            print_command_output(
                "Recommendation output",
                result.recommendation_result.stdout,
            )

        print("Workflow completed successfully.")
        print(f"Profile available at: {result.profile_path}")
        print(f"Jobs saved to: {result.jobs_output_path}")
        print(f"Recommendations saved to: {result.recommendations_output_path}")

        return 0

    except (CommandNotFoundError, CommandRunError, ValueError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())